import { ResumeDocument } from "@/types/resume";

export const createSampleResume = (
    id = "resume-sample",
    updatedAt = "2026-10-01T00:00:00.000Z"
): ResumeDocument => ({
    id,
    versionName: "샘플 이력서",
    updatedAt,
    globalStyle: {
        fontFamily: "'Pretendard', sans-serif",
        primaryColor: "#2f80c3",
        contentWidth: 800,
        basePadding: 36,
        blockGap: 18,
        displayTitleFontSize: 24,
        sectionTitleFontSize: 24,
        itemTitleFontSize: 15,
        bodyFontSize: 14,
        captionFontSize: 12,
        template: "modern",
    },
    blocks: [
        {
            id: "block-p-1",
            type: "profile",
            title: "PROFILE",
            isVisible: true,
            order: 0,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: {
                name: "김브릭",
                role: "Frontend Engineer",
                email: "birpick@coreluma.kr",
                phone: "010-0000-0000",
                bio: "복잡한 문제를 이해하기 쉬운 화면으로 풀어내는",
                photo: "/profile_default.png",
                showPhoto: true,
                blog: "https://coreluma.kr/blog",
                github: "https://coreluma.kr/example",
                contacts: [
                    { id: "contact-email", label: "Email", value: "birpick@coreluma.kr" },
                    { id: "contact-phone", label: "Phone", value: "010-0000-0000" },
                    { id: "contact-blog", label: "Blog", value: "https://coreluma.kr/blog" },
                    { id: "contact-github", label: "GitHub", value: "https://coreluma.kr/example", inlineWithPrevious: true },
                ],
                highlights: [
                    "React와 TypeScript를 기반으로 사용자 중심의 웹 제품을 개발합니다.",
                    "디자인 시스템과 테스트 자동화를 통해 팀의 개발 속도와 화면 품질을 함께 높였습니다.",
                    "사용자 행동 데이터와 고객 피드백을 바탕으로 제품의 문제를 정의하고 개선합니다.",
                ],
                introductionStyle: "bullets",
            },
        },
        {
            id: "block-s-1",
            type: "skills",
            title: "CORE SKILLS",
            isVisible: true,
            order: 1,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: {
                categories: [
                    { id: "skills-frontend", name: "Frontend", skills: ["React", "Next.js", "TypeScript", "TanStack Query"] },
                    { id: "skills-ui", name: "UI", skills: ["Tailwind CSS", "Storybook", "Figma", "Accessibility"] },
                    { id: "skills-quality", name: "Quality", skills: ["Vitest", "Playwright", "GitHub Actions"] },
                ],
            },
        },
        {
            id: "block-e-1",
            type: "experience",
            title: "WORK EXPERIENCE",
            isVisible: true,
            order: 2,
            style: { paddingY: 18, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "exp-sample-1",
                    company: "루미노스 커머스",
                    role: "Frontend Engineer",
                    startDate: "2023.04",
                    endDate: "재직 중",
                    description: [
                        "커머스 운영 도구와 고객용 웹 서비스의 프론트엔드 개발 및 운영",
                        "디자이너·백엔드 개발자와 협업해 공통 UI 정책과 배포 프로세스 정립",
                    ],
                    projects: [
                        {
                            id: "exp-project-sample-1",
                            title: "파트너 정산 대시보드",
                            role: "프론트엔드 설계 및 핵심 화면 개발",
                            startDate: "2024.02",
                            endDate: "2024.08",
                            description: [
                                "대용량 정산 내역을 빠르게 탐색할 수 있도록 서버 상태와 필터 상태를 분리해 설계",
                                "공통 테이블과 폼 컴포넌트를 구축해 신규 운영 화면 개발 시간을 약 35% 단축",
                                "Playwright 기반 주요 정산 시나리오 테스트를 도입해 배포 전 회귀 오류를 감소",
                            ],
                            descriptionLevels: [1, 1, 1],
                        },
                        {
                            id: "exp-project-sample-2",
                            title: "모바일 주문 경험 개선",
                            role: "상품 상세·장바구니 사용자 흐름 개선",
                            startDate: "2023.07",
                            endDate: "2023.12",
                            description: [
                                "이미지 로딩과 렌더링 병목을 개선해 모바일 LCP를 3.1초에서 1.8초로 단축",
                                "접근성 점검과 키보드 탐색 개선으로 핵심 구매 흐름의 사용성을 강화",
                            ],
                            descriptionLevels: [1, 1],
                        },
                    ],
                },
                {
                    id: "exp-sample-2",
                    company: "모노랩스",
                    role: "Frontend Developer",
                    startDate: "2021.07",
                    endDate: "2023.03",
                    description: [
                        "B2B 협업 서비스의 프론트엔드 기능 개발과 디자인 시스템 운영",
                        "제품 지표와 고객 문의를 기반으로 반복되는 사용성 문제를 발굴하고 개선",
                    ],
                    projects: [
                        {
                            id: "exp-project-sample-3",
                            title: "팀 협업 워크스페이스 개편",
                            role: "워크스페이스·권한 관리 화면 개발",
                            startDate: "2022.05",
                            endDate: "2023.01",
                            description: [
                                "복잡한 멤버 권한 정책을 역할 기반 UI로 재구성해 설정 과정의 고객 문의를 28% 감소",
                                "Storybook 기반 공통 컴포넌트를 정비해 화면 간 UI 일관성과 개발 생산성을 향상",
                            ],
                            descriptionLevels: [1, 1],
                        },
                    ],
                },
            ],
        },
        {
            id: "block-pr-1",
            type: "project",
            title: "NOTABLE PROJECTS",
            isVisible: true,
            order: 3,
            style: { paddingY: 18, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "proj-sample-1",
                    title: "RouteMate 여행 일정 플래너",
                    role: "사이드 프로젝트 · 프론트엔드 개발",
                    startDate: "2024.09",
                    endDate: "2025.01",
                    link: "https://github.com/example/routemate",
                    description: [
                        "지도 검색 결과와 일정 편집 상태를 동기화하는 드래그 앤 드롭 인터페이스 구현",
                        "공유 링크의 초기 데이터 로딩을 최적화해 첫 화면 표시 시간을 40% 단축",
                        "반응형 레이아웃과 오프라인 임시 저장으로 모바일 작성 경험 개선",
                    ],
                    descriptionLevels: [1, 1, 1],
                },
                {
                    id: "proj-sample-2",
                    title: "DevNote 기술 아카이브",
                    role: "개인 프로젝트 · 기획 및 프론트엔드 개발",
                    startDate: "2024.03",
                    endDate: "2024.06",
                    link: "https://github.com/example/devnote",
                    description: [
                        "Markdown 문서 작성과 태그 기반 검색을 지원하는 개인 기술 기록 서비스 개발",
                        "정적 생성과 이미지 최적화를 적용해 Lighthouse 성능 점수 95점 이상을 유지",
                    ],
                    descriptionLevels: [1, 1],
                },
                {
                    id: "proj-sample-3",
                    title: "Open UI Kit",
                    role: "오픈소스 · 컴포넌트 설계 및 문서화",
                    startDate: "2023.10",
                    endDate: "2024.02",
                    link: "https://github.com/example/open-ui-kit",
                    description: [
                        "접근성을 고려한 폼·모달·메뉴 컴포넌트 12종을 설계하고 사용 예제를 문서화",
                        "시각 회귀 테스트와 자동 배포 파이프라인을 구성해 기여 검증 과정을 자동화",
                    ],
                    descriptionLevels: [1, 1],
                },
            ],
        },
        {
            id: "block-edu-1",
            type: "education",
            title: "EDUCATION",
            isVisible: true,
            order: 4,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "edu-sample-1",
                    school: "브릭대학교",
                    major: "컴퓨터공학과",
                    startDate: "2019.03",
                    endDate: "2023.02",
                    status: "졸업",
                    score: "3.9 / 4.5",
                },
            ],
        },
        {
            id: "block-cert-1",
            type: "certification",
            title: "CERTIFICATIONS & AWARDS",
            isVisible: true,
            order: 5,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "cert-sample-1",
                    title: "정보처리기사",
                    issuer: "한국산업인력공단",
                    date: "2023.06",
                    description: "소프트웨어 설계·개발 및 데이터베이스 활용 역량 검증",
                },
                {
                    id: "cert-sample-2",
                    title: "SQL 개발자(SQLD)",
                    issuer: "한국데이터산업진흥원",
                    date: "2022.09",
                    description: "데이터 모델링과 SQL 활용 능력 검증",
                },
                {
                    id: "cert-sample-3",
                    title: "사내 제품 개선 해커톤 최우수상",
                    issuer: "루미노스 커머스",
                    date: "2024.11",
                    description: "고객 문의 자동 분류 대시보드를 제안하고 프로토타입을 구현",
                },
            ],
        },
        {
            id: "block-custom-1",
            type: "custom_text",
            title: "ADDITIONAL INFORMATION",
            isVisible: true,
            order: 6,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: {
                content: "기술을 쉽게 설명하고 팀의 지식을 문서로 남기는 일을 좋아합니다. 사내 프론트엔드 스터디를 운영하며 학습 내용을 꾸준히 공유하고 있습니다.",
            },
        },
    ],
});
