import { ResumeDocument } from "@/types/resume";

export const createSampleResume = (
    id = "resume-sample",
    updatedAt = "2026-10-01T00:00:00.000Z"
): ResumeDocument => ({
    id,
    versionName: "샘플 이력서",
    updatedAt,
    globalStyle: {
        fontFamily: "'Pretendard', sans-serif",
        primaryColor: "#2f80c3",
        contentWidth: 800,
        basePadding: 36,
        blockGap: 18,
        displayTitleFontSize: 24,
        sectionTitleFontSize: 24,
        itemTitleFontSize: 19,
        bodyFontSize: 14,
        captionFontSize: 14,
        template: "modern",
    },
    blocks: [
        {
            id: "block-p-1",
            type: "profile",
            title: "PROFILE",
            isVisible: true,
            order: 0,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: {
                name: "김브릭",
                role: "Frontend Engineer",
                email: "birpick@coreluma.kr",
                phone: "010-1234-5678",
                bio: "복잡한 문제를 이해하기 쉬운 화면으로 풀어내는",
                photo: "/profile_default.png",
                showPhoto: true,
                blog: "https://coreluma.kr/blog",
                github: "https://coreluma.kr/example",
                contacts: [
                    { id: "contact-email", label: "Email", value: "birpick@coreluma.kr" },
                    { id: "contact-phone", label: "Phone", value: "010-1234-5678" },
                    { id: "contact-blog", label: "Blog", value: "https://coreluma.kr/blog" },
                    { id: "contact-github", label: "GitHub", value: "https://coreluma.kr/example", inlineWithPrevious: true },
                ],
                highlights: [
                    "React와 TypeScript를 기반으로 사용자 중심의 웹 제품을 개발합니다.",
                    "디자인 시스템과 테스트 자동화를 통해 팀의 개발 속도와 화면 품질을 함께 높였습니다.",
                    "사용자 행동 데이터와 고객 피드백을 바탕으로 제품의 문제를 정의하고 개선합니다.",
                ],
                introductionStyle: "bullets",
            },
        },
        {
            id: "block-s-1",
            type: "skills",
            title: "CORE SKILLS",
            isVisible: true,
            order: 1,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: {
                categories: [
                    { id: "skills-frontend", name: "Frontend", skills: ["React", "Next.js", "TypeScript", "TanStack Query"] },
                    { id: "skills-ui", name: "UI", skills: ["Tailwind CSS", "Storybook", "Figma", "Accessibility"] },
                    { id: "skills-quality", name: "Quality", skills: ["Vitest", "Playwright", "GitHub Actions"] },
                ],
            },
        },
        {
            id: "block-e-1",
            type: "experience",
            title: "WORK EXPERIENCE",
            isVisible: true,
            order: 2,
            style: { paddingY: 18, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "exp-sample-1",
                    company: "루미노스 커머스",
                    role: "Frontend Engineer",
                    startDate: "2023.04",
                    endDate: "재직 중",
                    description: [
                        "커머스 운영 도구와 고객용 웹 서비스의 프론트엔드 개발 및 운영",
                        "디자이너·백엔드 개발자와 협업해 공통 UI 정책과 배포 프로세스 정립",
                    ],
                    projects: [
                        {
                            id: "exp-project-sample-1",
                            title: "파트너 정산 대시보드",
                            role: "프론트엔드 설계 및 핵심 화면 개발",
                            startDate: "2024.02",
                            endDate: "2024.08",
                            description: [
                                "담당 업무: 정산 대시보드 화면 구조 설계 및 핵심 사용자 흐름 개발",
                                "주요 성과 및 의의",
                                "서버 상태와 필터 상태를 분리해 대용량 정산 내역의 탐색 성능 개선",
                                "공통 테이블과 폼 컴포넌트를 구축해 신규 운영 화면 개발 시간을 약 35% 단축",
                                "Playwright 기반 회귀 테스트로 배포 전 정산 오류 감소",
                                "주요 기술: React, TypeScript, TanStack Query, Playwright",
                            ],
                            descriptionLevels: [1, 1, 2, 3, 3, 1],
                            descriptionHtml: [
                                "<strong>담당 업무 :</strong> 정산 대시보드 화면 구조 설계 및 핵심 사용자 흐름 개발",
                                "<strong>주요 성과 및 의의</strong>",
                                "서버 상태와 필터 상태를 분리해 <strong>대용량 정산 내역의 탐색 성능 개선</strong>",
                                "공통 테이블과 폼 컴포넌트를 구축해 <strong>신규 운영 화면 개발 시간을 약 35% 단축</strong>",
                                "Playwright 기반 회귀 테스트로 <strong>배포 전 정산 오류 감소</strong>",
                                "<strong>주요 기술 :</strong> React, TypeScript, TanStack Query, Playwright",
                            ],
                        },
                        {
                            id: "exp-project-sample-2",
                            title: "모바일 주문 경험 개선",
                            role: "상품 상세·장바구니 사용자 흐름 개선",
                            startDate: "2023.07",
                            endDate: "2023.12",
                            description: [
                                "담당 업무: 상품 상세부터 장바구니까지 이어지는 모바일 구매 흐름 개선",
                                "주요 성과 및 의의",
                                "이미지 로딩과 렌더링 병목을 개선해 모바일 LCP를 3.1초에서 1.8초로 단축",
                                "접근성 점검과 키보드 탐색 개선으로 핵심 구매 흐름의 사용성 강화",
                                "주요 기술: Next.js, TypeScript, Web Vitals",
                            ],
                            descriptionLevels: [1, 1, 2, 3, 1],
                            descriptionHtml: [
                                "<strong>담당 업무 :</strong> 상품 상세부터 장바구니까지 이어지는 모바일 구매 흐름 개선",
                                "<strong>주요 성과 및 의의</strong>",
                                "이미지 로딩과 렌더링 병목을 개선해 <strong>모바일 LCP를 3.1초에서 1.8초로 단축</strong>",
                                "접근성 점검과 키보드 탐색 개선으로 <strong>핵심 구매 흐름의 사용성 강화</strong>",
                                "<strong>주요 기술 :</strong> Next.js, TypeScript, Web Vitals",
                            ],
                        },
                    ],
                },
                {
                    id: "exp-sample-2",
                    company: "모노랩스",
                    role: "Frontend Developer",
                    startDate: "2021.07",
                    endDate: "2023.03",
                    description: [
                        "B2B 협업 서비스의 프론트엔드 기능 개발과 디자인 시스템 운영",
                        "제품 지표와 고객 문의를 기반으로 반복되는 사용성 문제를 발굴하고 개선",
                    ],
                    projects: [
                        {
                            id: "exp-project-sample-3",
                            title: "팀 협업 워크스페이스 개편",
                            role: "워크스페이스·권한 관리 화면 개발",
                            startDate: "2022.05",
                            endDate: "2023.01",
                            description: [
                                "담당 업무: 워크스페이스 멤버와 역할별 권한 관리 화면 개발",
                                "주요 성과 및 의의",
                                "복잡한 권한 정책을 역할 기반 UI로 재구성해 설정 과정의 고객 문의를 28% 감소",
                                "Storybook 기반 공통 컴포넌트를 정비해 화면 간 UI 일관성과 개발 생산성 향상",
                                "주요 기술: React, Storybook, React Testing Library",
                            ],
                            descriptionLevels: [1, 1, 2, 3, 1],
                            descriptionHtml: [
                                "<strong>담당 업무 :</strong> 워크스페이스 멤버와 역할별 권한 관리 화면 개발",
                                "<strong>주요 성과 및 의의</strong>",
                                "복잡한 권한 정책을 역할 기반 UI로 재구성해 <strong>설정 관련 고객 문의를 28% 감소</strong>",
                                "Storybook 기반 공통 컴포넌트를 정비해 <strong>UI 일관성과 개발 생산성 향상</strong>",
                                "<strong>주요 기술 :</strong> React, Storybook, React Testing Library",
                            ],
                        },
                    ],
                },
            ],
        },
        {
            id: "block-pr-1",
            type: "project",
            title: "NOTABLE PROJECTS",
            isVisible: true,
            order: 3,
            style: { paddingY: 18, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "proj-sample-1",
                    title: "RouteMate 여행 일정 플래너",
                    role: "사이드 프로젝트 · 프론트엔드 개발",
                    startDate: "2024.09",
                    endDate: "2025.01",
                    link: "https://github.com/example/routemate",
                    description: [
                        "담당 업무: 지도 검색과 일정 편집을 연결하는 사용자 흐름 설계 및 구현",
                        "주요 성과 및 의의",
                        "드래그 앤 드롭으로 장소 순서를 변경하고 지도 마커와 일정 상태를 실시간 동기화",
                        "공유 링크 초기 로딩을 최적화해 첫 화면 표시 시간을 40% 단축",
                        "오프라인 임시 저장을 적용해 네트워크가 불안정한 환경에서도 작성 내용 유지",
                        "주요 기술: Next.js, TypeScript, dnd-kit, IndexedDB",
                    ],
                    descriptionLevels: [1, 1, 2, 3, 3, 1],
                    descriptionHtml: [
                        "<strong>담당 업무 :</strong> 지도 검색과 일정 편집을 연결하는 사용자 흐름 설계 및 구현",
                        "<strong>주요 성과 및 의의</strong>",
                        "드래그 앤 드롭으로 장소 순서를 변경하고 <strong>지도 마커와 일정 상태를 실시간 동기화</strong>",
                        "공유 링크 초기 로딩을 최적화해 <strong>첫 화면 표시 시간을 40% 단축</strong>",
                        "오프라인 임시 저장을 적용해 <strong>네트워크가 불안정한 환경에서도 작성 내용 유지</strong>",
                        "<strong>주요 기술 :</strong> Next.js, TypeScript, dnd-kit, IndexedDB",
                    ],
                },
                {
                    id: "proj-sample-2",
                    title: "DevNote 기술 아카이브",
                    role: "개인 프로젝트 · 기획 및 프론트엔드 개발",
                    startDate: "2024.03",
                    endDate: "2024.06",
                    link: "https://github.com/example/devnote",
                    description: [
                        "담당 업무: Markdown 기반 기술 문서 작성·검색 기능 개발",
                        "주요 성과 및 의의",
                        "태그와 전문 검색을 결합해 기록 탐색 시간을 단축",
                        "정적 생성과 이미지 최적화로 Lighthouse 성능 점수 95점 이상 유지",
                        "주요 기술: Next.js, MDX, Fuse.js",
                    ],
                    descriptionLevels: [1, 1, 2, 3, 1],
                    descriptionHtml: [
                        "<strong>담당 업무 :</strong> Markdown 기반 기술 문서 작성·검색 기능 개발",
                        "<strong>주요 성과 및 의의</strong>",
                        "태그와 전문 검색을 결합해 <strong>기록 탐색 시간을 단축</strong>",
                        "정적 생성과 이미지 최적화로 <strong>Lighthouse 성능 점수 95점 이상 유지</strong>",
                        "<strong>주요 기술 :</strong> Next.js, MDX, Fuse.js",
                    ],
                },
                {
                    id: "proj-sample-3",
                    title: "Open UI Kit",
                    role: "오픈소스 · 컴포넌트 설계 및 문서화",
                    startDate: "2023.10",
                    endDate: "2024.02",
                    link: "https://github.com/example/open-ui-kit",
                    description: [
                        "담당 업무: 접근성을 고려한 공통 UI 컴포넌트 설계 및 문서화",
                        "주요 성과 및 의의",
                        "폼·모달·메뉴 컴포넌트 12종에 키보드 탐색과 ARIA 속성 적용",
                        "시각 회귀 테스트와 자동 배포로 오픈소스 기여 검증 과정 자동화",
                        "주요 기술: React, Storybook, Playwright, GitHub Actions",
                    ],
                    descriptionLevels: [1, 1, 2, 3, 1],
                    descriptionHtml: [
                        "<strong>담당 업무 :</strong> 접근성을 고려한 공통 UI 컴포넌트 설계 및 문서화",
                        "<strong>주요 성과 및 의의</strong>",
                        "폼·모달·메뉴 컴포넌트 12종에 <strong>키보드 탐색과 ARIA 속성 적용</strong>",
                        "시각 회귀 테스트와 자동 배포로 <strong>오픈소스 기여 검증 과정 자동화</strong>",
                        "<strong>주요 기술 :</strong> React, Storybook, Playwright, GitHub Actions",
                    ],
                },
            ],
        },
        {
            id: "block-edu-1",
            type: "education",
            title: "EDUCATION",
            isVisible: true,
            order: 4,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "edu-sample-1",
                    school: "브릭대학교",
                    major: "컴퓨터공학과",
                    startDate: "2019.03",
                    endDate: "2023.02",
                    status: "졸업",
                    score: "3.9 / 4.5",
                },
            ],
        },
        {
            id: "block-cert-1",
            type: "certification",
            title: "Other Experience",
            isVisible: true,
            order: 5,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: [
                {
                    id: "cert-sample-1",
                    title: "오픈소스 UI 라이브러리 기여",
                    startDate: "2024.03",
                    endDate: "2024.08",
                    link: "https://github.com",
                    description: [
                        "키보드 탐색과 포커스 이동 관련 접근성 오류 개선",
                        "공통 컴포넌트 사용 가이드와 Storybook 예제 보강",
                        "GitHub Issue와 Pull Request 기반 비동기 협업 경험",
                    ],
                    descriptionHtml: [
                        "키보드 탐색과 포커스 이동 관련 <strong>접근성 오류 개선</strong>",
                        "공통 컴포넌트 사용 가이드와 Storybook 예제 보강",
                        "GitHub Issue와 Pull Request 기반 비동기 협업 경험",
                    ],
                },
                {
                    id: "cert-sample-2",
                    title: "프론트엔드 스터디 운영",
                    startDate: "2023.09",
                    endDate: "2024.02",
                    description: [
                        "주 1회 기술 발표와 코드 리뷰를 포함한 12주 과정 설계",
                        "React 렌더링과 웹 성능을 주제로 실습 자료 제작",
                        "회고를 바탕으로 다음 기수 완주율을 70%에서 90%로 개선",
                    ],
                    descriptionHtml: [
                        "주 1회 기술 발표와 코드 리뷰를 포함한 <strong>12주 과정 설계</strong>",
                        "React 렌더링과 웹 성능을 주제로 실습 자료 제작",
                        "회고를 바탕으로 다음 기수 <strong>완주율을 70%에서 90%로 개선</strong>",
                    ],
                },
                {
                    id: "cert-sample-3",
                    title: "지역 생활 편의 해커톤",
                    startDate: "2023.07",
                    endDate: "",
                    description: [
                        "생활 편의시설 혼잡도를 알려주는 모바일 웹 서비스 기획",
                        "사용자 인터뷰 결과를 반영해 핵심 탐색 단계를 5단계에서 3단계로 단축",
                        "48시간 내 프로토타입을 완성하고 사용자 경험 부문 우수상 수상",
                    ],
                    descriptionHtml: [
                        "생활 편의시설 혼잡도를 알려주는 <strong>모바일 웹 서비스 기획</strong>",
                        "사용자 인터뷰 결과를 반영해 핵심 탐색 단계를 <strong>5단계에서 3단계로 단축</strong>",
                        "48시간 내 프로토타입을 완성하고 <strong>사용자 경험 부문 우수상</strong> 수상",
                    ],
                },
            ],
        },
        {
            id: "block-custom-1",
            type: "custom_text",
            title: "ADDITIONAL INFORMATION",
            isVisible: true,
            order: 6,
            style: { paddingY: 16, paddingX: 0, columns: 1, showDivider: true },
            data: {
                content: "기술을 쉽게 설명하고 팀의 지식을 문서로 남기는 일을 좋아합니다. 사내 프론트엔드 스터디를 운영하며 학습 내용을 꾸준히 공유하고 있습니다.",
            },
        },
    ],
});
